// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: planner/planner.proto

package planner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PlannerService_GeneratePlan_FullMethodName = "/planner.PlannerService/GeneratePlan"
	PlannerService_UpdatePlan_FullMethodName   = "/planner.PlannerService/UpdatePlan"
	PlannerService_ExecutePlan_FullMethodName  = "/planner.PlannerService/ExecutePlan"
)

// PlannerServiceClient is the client API for PlannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlannerServiceClient interface {
	GeneratePlan(ctx context.Context, in *GeneratePlanRequest, opts ...grpc.CallOption) (*GeneratePlanResponse, error)
	UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...grpc.CallOption) (*UpdatePlanResponse, error)
	ExecutePlan(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (PlannerService_ExecutePlanClient, error)
}

type plannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlannerServiceClient(cc grpc.ClientConnInterface) PlannerServiceClient {
	return &plannerServiceClient{cc}
}

func (c *plannerServiceClient) GeneratePlan(ctx context.Context, in *GeneratePlanRequest, opts ...grpc.CallOption) (*GeneratePlanResponse, error) {
	out := new(GeneratePlanResponse)
	err := c.cc.Invoke(ctx, PlannerService_GeneratePlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plannerServiceClient) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...grpc.CallOption) (*UpdatePlanResponse, error) {
	out := new(UpdatePlanResponse)
	err := c.cc.Invoke(ctx, PlannerService_UpdatePlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plannerServiceClient) ExecutePlan(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (PlannerService_ExecutePlanClient, error) {
	stream, err := c.cc.NewStream(ctx, &PlannerService_ServiceDesc.Streams[0], PlannerService_ExecutePlan_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &plannerServiceExecutePlanClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlannerService_ExecutePlanClient interface {
	Recv() (*ExecuteResponse, error)
	grpc.ClientStream
}

type plannerServiceExecutePlanClient struct {
	grpc.ClientStream
}

func (x *plannerServiceExecutePlanClient) Recv() (*ExecuteResponse, error) {
	m := new(ExecuteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PlannerServiceServer is the server API for PlannerService service.
// All implementations must embed UnimplementedPlannerServiceServer
// for forward compatibility
type PlannerServiceServer interface {
	GeneratePlan(context.Context, *GeneratePlanRequest) (*GeneratePlanResponse, error)
	UpdatePlan(context.Context, *UpdatePlanRequest) (*UpdatePlanResponse, error)
	ExecutePlan(*ExecuteRequest, PlannerService_ExecutePlanServer) error
	mustEmbedUnimplementedPlannerServiceServer()
}

// UnimplementedPlannerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlannerServiceServer struct {
}

func (UnimplementedPlannerServiceServer) GeneratePlan(context.Context, *GeneratePlanRequest) (*GeneratePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePlan not implemented")
}
func (UnimplementedPlannerServiceServer) UpdatePlan(context.Context, *UpdatePlanRequest) (*UpdatePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlan not implemented")
}
func (UnimplementedPlannerServiceServer) ExecutePlan(*ExecuteRequest, PlannerService_ExecutePlanServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecutePlan not implemented")
}
func (UnimplementedPlannerServiceServer) mustEmbedUnimplementedPlannerServiceServer() {}

// UnsafePlannerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlannerServiceServer will
// result in compilation errors.
type UnsafePlannerServiceServer interface {
	mustEmbedUnimplementedPlannerServiceServer()
}

func RegisterPlannerServiceServer(s grpc.ServiceRegistrar, srv PlannerServiceServer) {
	s.RegisterService(&PlannerService_ServiceDesc, srv)
}

func _PlannerService_GeneratePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServiceServer).GeneratePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlannerService_GeneratePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServiceServer).GeneratePlan(ctx, req.(*GeneratePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlannerService_UpdatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServiceServer).UpdatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlannerService_UpdatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServiceServer).UpdatePlan(ctx, req.(*UpdatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlannerService_ExecutePlan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlannerServiceServer).ExecutePlan(m, &plannerServiceExecutePlanServer{stream})
}

type PlannerService_ExecutePlanServer interface {
	Send(*ExecuteResponse) error
	grpc.ServerStream
}

type plannerServiceExecutePlanServer struct {
	grpc.ServerStream
}

func (x *plannerServiceExecutePlanServer) Send(m *ExecuteResponse) error {
	return x.ServerStream.SendMsg(m)
}

// PlannerService_ServiceDesc is the grpc.ServiceDesc for PlannerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "planner.PlannerService",
	HandlerType: (*PlannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePlan",
			Handler:    _PlannerService_GeneratePlan_Handler,
		},
		{
			MethodName: "UpdatePlan",
			Handler:    _PlannerService_UpdatePlan_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecutePlan",
			Handler:       _PlannerService_ExecutePlan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "planner/planner.proto",
}
