// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: knowledge/knowledge.proto

package knowledge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	KnowledgeService_CreatePRD_FullMethodName           = "/knowledge.KnowledgeService/CreatePRD"
	KnowledgeService_GenerateUserStories_FullMethodName = "/knowledge.KnowledgeService/GenerateUserStories"
)

// KnowledgeServiceClient is the client API for KnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeServiceClient interface {
	CreatePRD(ctx context.Context, in *CreatePRDRequest, opts ...grpc.CallOption) (*CreatePRDResponse, error)
	GenerateUserStories(ctx context.Context, in *GenerateUserStoriesRequest, opts ...grpc.CallOption) (*GenerateUserStoriesResponse, error)
}

type knowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeServiceClient(cc grpc.ClientConnInterface) KnowledgeServiceClient {
	return &knowledgeServiceClient{cc}
}

func (c *knowledgeServiceClient) CreatePRD(ctx context.Context, in *CreatePRDRequest, opts ...grpc.CallOption) (*CreatePRDResponse, error) {
	out := new(CreatePRDResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_CreatePRD_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GenerateUserStories(ctx context.Context, in *GenerateUserStoriesRequest, opts ...grpc.CallOption) (*GenerateUserStoriesResponse, error) {
	out := new(GenerateUserStoriesResponse)
	err := c.cc.Invoke(ctx, KnowledgeService_GenerateUserStories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServiceServer is the server API for KnowledgeService service.
// All implementations must embed UnimplementedKnowledgeServiceServer
// for forward compatibility
type KnowledgeServiceServer interface {
	CreatePRD(context.Context, *CreatePRDRequest) (*CreatePRDResponse, error)
	GenerateUserStories(context.Context, *GenerateUserStoriesRequest) (*GenerateUserStoriesResponse, error)
	mustEmbedUnimplementedKnowledgeServiceServer()
}

// UnimplementedKnowledgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKnowledgeServiceServer struct {
}

func (UnimplementedKnowledgeServiceServer) CreatePRD(context.Context, *CreatePRDRequest) (*CreatePRDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePRD not implemented")
}
func (UnimplementedKnowledgeServiceServer) GenerateUserStories(context.Context, *GenerateUserStoriesRequest) (*GenerateUserStoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateUserStories not implemented")
}
func (UnimplementedKnowledgeServiceServer) mustEmbedUnimplementedKnowledgeServiceServer() {}

// UnsafeKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServiceServer will
// result in compilation errors.
type UnsafeKnowledgeServiceServer interface {
	mustEmbedUnimplementedKnowledgeServiceServer()
}

func RegisterKnowledgeServiceServer(s grpc.ServiceRegistrar, srv KnowledgeServiceServer) {
	s.RegisterService(&KnowledgeService_ServiceDesc, srv)
}

func _KnowledgeService_CreatePRD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePRDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).CreatePRD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_CreatePRD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).CreatePRD(ctx, req.(*CreatePRDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GenerateUserStories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUserStoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GenerateUserStories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GenerateUserStories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GenerateUserStories(ctx, req.(*GenerateUserStoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeService_ServiceDesc is the grpc.ServiceDesc for KnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledge.KnowledgeService",
	HandlerType: (*KnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePRD",
			Handler:    _KnowledgeService_CreatePRD_Handler,
		},
		{
			MethodName: "GenerateUserStories",
			Handler:    _KnowledgeService_GenerateUserStories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowledge/knowledge.proto",
}
