// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: knowledge/knowledge.proto

package knowledge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePRDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId   string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreatePRDRequest) Reset() {
	*x = CreatePRDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_knowledge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePRDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePRDRequest) ProtoMessage() {}

func (x *CreatePRDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePRDRequest.ProtoReflect.Descriptor instead.
func (*CreatePRDRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePRDRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreatePRDRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePRDRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePRDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId string `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content    string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CreatePRDResponse) Reset() {
	*x = CreatePRDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_knowledge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePRDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePRDResponse) ProtoMessage() {}

func (x *CreatePRDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePRDResponse.ProtoReflect.Descriptor instead.
func (*CreatePRDResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePRDResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreatePRDResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenerateUserStoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrdContent string `protobuf:"bytes,1,opt,name=prd_content,json=prdContent,proto3" json:"prd_content,omitempty"`
}

func (x *GenerateUserStoriesRequest) Reset() {
	*x = GenerateUserStoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_knowledge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUserStoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUserStoriesRequest) ProtoMessage() {}

func (x *GenerateUserStoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUserStoriesRequest.ProtoReflect.Descriptor instead.
func (*GenerateUserStoriesRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateUserStoriesRequest) GetPrdContent() string {
	if x != nil {
		return x.PrdContent
	}
	return ""
}

type GenerateUserStoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoriesJson string `protobuf:"bytes,1,opt,name=stories_json,json=storiesJson,proto3" json:"stories_json,omitempty"`
}

func (x *GenerateUserStoriesResponse) Reset() {
	*x = GenerateUserStoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledge_knowledge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUserStoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUserStoriesResponse) ProtoMessage() {}

func (x *GenerateUserStoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_knowledge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUserStoriesResponse.ProtoReflect.Descriptor instead.
func (*GenerateUserStoriesResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateUserStoriesResponse) GetStoriesJson() string {
	if x != nil {
		return x.StoriesJson
	}
	return ""
}

var File_knowledge_knowledge_proto protoreflect.FileDescriptor

var file_knowledge_knowledge_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x6b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x22, 0x69, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x52, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x4e, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x52, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x3d, 0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x40, 0x0a, 0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x4a, 0x73,
	0x6f, 0x6e, 0x32, 0xc0, 0x01, 0x0a, 0x10, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x52, 0x44, 0x12, 0x1b, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x52, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x52, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x64, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x63, 0x76, 0x6e, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x3b, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_knowledge_knowledge_proto_rawDescOnce sync.Once
	file_knowledge_knowledge_proto_rawDescData = file_knowledge_knowledge_proto_rawDesc
)

func file_knowledge_knowledge_proto_rawDescGZIP() []byte {
	file_knowledge_knowledge_proto_rawDescOnce.Do(func() {
		file_knowledge_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(file_knowledge_knowledge_proto_rawDescData)
	})
	return file_knowledge_knowledge_proto_rawDescData
}

var file_knowledge_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_knowledge_knowledge_proto_goTypes = []interface{}{
	(*CreatePRDRequest)(nil),            // 0: knowledge.CreatePRDRequest
	(*CreatePRDResponse)(nil),           // 1: knowledge.CreatePRDResponse
	(*GenerateUserStoriesRequest)(nil),  // 2: knowledge.GenerateUserStoriesRequest
	(*GenerateUserStoriesResponse)(nil), // 3: knowledge.GenerateUserStoriesResponse
}
var file_knowledge_knowledge_proto_depIdxs = []int32{
	0, // 0: knowledge.KnowledgeService.CreatePRD:input_type -> knowledge.CreatePRDRequest
	2, // 1: knowledge.KnowledgeService.GenerateUserStories:input_type -> knowledge.GenerateUserStoriesRequest
	1, // 2: knowledge.KnowledgeService.CreatePRD:output_type -> knowledge.CreatePRDResponse
	3, // 3: knowledge.KnowledgeService.GenerateUserStories:output_type -> knowledge.GenerateUserStoriesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_knowledge_knowledge_proto_init() }
func file_knowledge_knowledge_proto_init() {
	if File_knowledge_knowledge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_knowledge_knowledge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePRDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_knowledge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePRDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_knowledge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateUserStoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledge_knowledge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateUserStoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_knowledge_knowledge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledge_knowledge_proto_goTypes,
		DependencyIndexes: file_knowledge_knowledge_proto_depIdxs,
		MessageInfos:      file_knowledge_knowledge_proto_msgTypes,
	}.Build()
	File_knowledge_knowledge_proto = out.File
	file_knowledge_knowledge_proto_rawDesc = nil
	file_knowledge_knowledge_proto_goTypes = nil
	file_knowledge_knowledge_proto_depIdxs = nil
}
