// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: ai_agents/ai_agents.proto

package ai_agentspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AIAgentsService_GetAgent_FullMethodName   = "/ai_agents.AIAgentsService/GetAgent"
	AIAgentsService_ListAgents_FullMethodName = "/ai_agents.AIAgentsService/ListAgents"
	AIAgentsService_GetSkill_FullMethodName   = "/ai_agents.AIAgentsService/GetSkill"
	AIAgentsService_ListSkills_FullMethodName = "/ai_agents.AIAgentsService/ListSkills"
)

// AIAgentsServiceClient is the client API for AIAgentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIAgentsServiceClient interface {
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*GetSkillResponse, error)
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
}

type aIAgentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIAgentsServiceClient(cc grpc.ClientConnInterface) AIAgentsServiceClient {
	return &aIAgentsServiceClient{cc}
}

func (c *aIAgentsServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, AIAgentsService_GetAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAgentsServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AIAgentsService_ListAgents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAgentsServiceClient) GetSkill(ctx context.Context, in *GetSkillRequest, opts ...grpc.CallOption) (*GetSkillResponse, error) {
	out := new(GetSkillResponse)
	err := c.cc.Invoke(ctx, AIAgentsService_GetSkill_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAgentsServiceClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, AIAgentsService_ListSkills_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIAgentsServiceServer is the server API for AIAgentsService service.
// All implementations must embed UnimplementedAIAgentsServiceServer
// for forward compatibility
type AIAgentsServiceServer interface {
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error)
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	mustEmbedUnimplementedAIAgentsServiceServer()
}

// UnimplementedAIAgentsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIAgentsServiceServer struct {
}

func (UnimplementedAIAgentsServiceServer) GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAIAgentsServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAIAgentsServiceServer) GetSkill(context.Context, *GetSkillRequest) (*GetSkillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkill not implemented")
}
func (UnimplementedAIAgentsServiceServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedAIAgentsServiceServer) mustEmbedUnimplementedAIAgentsServiceServer() {}

// UnsafeAIAgentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIAgentsServiceServer will
// result in compilation errors.
type UnsafeAIAgentsServiceServer interface {
	mustEmbedUnimplementedAIAgentsServiceServer()
}

func RegisterAIAgentsServiceServer(s grpc.ServiceRegistrar, srv AIAgentsServiceServer) {
	s.RegisterService(&AIAgentsService_ServiceDesc, srv)
}

func _AIAgentsService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentsServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgentsService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentsServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAgentsService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentsServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgentsService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentsServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAgentsService_GetSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentsServiceServer).GetSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgentsService_GetSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentsServiceServer).GetSkill(ctx, req.(*GetSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAgentsService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentsServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgentsService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentsServiceServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIAgentsService_ServiceDesc is the grpc.ServiceDesc for AIAgentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIAgentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_agents.AIAgentsService",
	HandlerType: (*AIAgentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgent",
			Handler:    _AIAgentsService_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AIAgentsService_ListAgents_Handler,
		},
		{
			MethodName: "GetSkill",
			Handler:    _AIAgentsService_GetSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _AIAgentsService_ListSkills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_agents/ai_agents.proto",
}
